const express = require('express');
const router = express.Router();
const EngraisController = require('../../Controller/ProductionAgriculture/historiqueEngrais');
const authenticateUser= require('../../Controller/Authentification/authenticateUser');
router.post('/', authenticateUser,EngraisController.create);
router.get('/:id',EngraisController.get);
router.delete('/:id',EngraisController.delete);
router.put('/:id',EngraisController.update);
router.get('/engrais/:id',EngraisController.getById);
module.exports = router;