const express = require('express');
const router = express.Router();
const categorieBetailController = require('../../Controller/Betail/CategorieBétail');
router.post('/', categorieBetailController.create);
router.get('/', categorieBetailController.all);
router.get('/:id', categorieBetailController.getCategorieById);
router.put('/modifier/:id', categorieBetailController.update);
router.delete('/delete/:id', categorieBetailController.delete);
router.get('/categories/races/:id', categorieBetailController.getRaces);
module.exports = router;