const express = require('express');
const router = express.Router();
const AnimalController = require('../../Controller/Betail/FicheAnimalController');
const authenticateUser= require('../../Controller/Authentification/authenticateUser');
router.post('/', authenticateUser,AnimalController.create);
router.get('/',authenticateUser,AnimalController.getAnimauxByAgriculteur);
router.get('/all',AnimalController.all);
router.delete('/:id',AnimalController.delete);
router.put('/:id',AnimalController.update);
router.get('/:id',AnimalController.getbetailById);
module.exports = router;